---
- name: Set OSPF configuration
  cisco.ios.ios_config:
    lines:
    - netw 10.10.9.0 0.0.0.255 area 0
    - netw 10.10.10.0 0.0.0.255 area 1
    - netw 10.10.11.0 0.0.0.255 area 1
    - netw 10.10.12.0 0.0.0.255 area 1
    - netw 10.10.13.0 0.0.0.255 area 1
    parents: router ospf 1
