---
- name: config
  hosts: R1
  connection: local
  gather_facts: no
  tasks:
    - name: configure provider
      set_fact:
        provider:
          username: sistel
          password: sistel

    - name: configure top level configuration
      ios_config:
        lines: hostname {{ inventory_hostname }}
        timeout: 30
        provider: "{{provider}}"

  roles:
    - r1_ip
    - r1_ospf
