---
- name: Set OSPF configuration
  cisco.ios.ios_config:
    lines:
    - netw 10.10.10.0 0.0.0.255 area 1
    - netw 10.10.14.0 0.0.0.255 area 1
    - netw 10.10.15.0 0.0.0.255 area 1
    - netw 10.10.16.0 0.0.0.255 area 1
    parents: router ospf 1
