---
- name: interface IP address
  ios_config:
    provider:
      username: sistel
      password: sistel
    timeout: 30
    lines:
      - ip address 10.10.10.2 255.255.255.0
      - no shutdown
    parents: interface GigabitEthernet 0/1

- name: interface IP address
  ios_config:
    provider:
      username: sistel
      password: sistel
    timeout: 30
    lines:
      - ip address 11.11.11.1 255.255.255.0
      - no shutdown
    parents: interface GigabitEthernet 0/2

- name: interface IP address
  ios_config:
    provider:
      username: sistel
      password: sistel
    timeout: 30
    lines:
      - ip address 192.168.20.1 255.255.255.0
      - no shutdown
    parents: interface GigabitEthernet 0/3
