---
- name: Set OSPF configuration
  cisco.ios.ios_config:
    lines:
    - netw 10.20.18.0 0.0.0.255 area 1
    - netw 10.20.16.0 0.0.0.255 area 1
    - netw 10.20.19.0 0.0.0.255 area 1
    - netw 10.10.13.0 0.0.0.255 area 1
    parents: router ospf 1
